apiVersion: 1

datasources:
  - name: Prometheus
    uid: chalice-prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      manageAlerts: false
